// quizVocabulary.js - Base de vocabulario masiva (1000+ palabras)

export const VOCABULARY_BASICO = {
    // ANIMALES (50+ palabras)
    animales: [
        { es: 'perro', pt: 'cachorro' }, { es: 'gato', pt: 'gato' }, { es: 'pájaro', pt: 'pássaro' },
        { es: 'caballo', pt: 'cavalo' }, { es: 'vaca', pt: 'vaca' }, { es: 'cerdo', pt: 'porco' },
        { es: 'oveja', pt: 'ovelha' }, { es: 'gallina', pt: 'galinha' }, { es: 'pez', pt: 'peixe' },
        { es: 'mariposa', pt: 'borboleta' }, { es: 'abeja', pt: 'abelha' }, { es: 'hormiga', pt: 'formiga' },
        { es: 'león', pt: 'leão' }, { es: 'tigre', pt: 'tigre' }, { es: 'elefante', pt: 'elefante' },
        { es: 'jirafa', pt: 'girafa' }, { es: 'mono', pt: 'macaco' }, { es: 'serpiente', pt: 'cobra' },
        { es: 'cocodrilo', pt: 'crocodilo' }, { es: 'oso', pt: 'urso' }, { es: 'lobo', pt: 'lobo' },
        { es: 'zorro', pt: 'raposa' }, { es: 'conejo', pt: 'coelho' }, { es: 'ratón', pt: 'rato' },
        { es: 'ballena', pt: 'baleia' }, { es: 'delfín', pt: 'golfinho' }, { es: 'tiburón', pt: 'tubarão' },
        { es: 'pulpo', pt: 'polvo' }, { es: 'cangrejo', pt: 'caranguejo' }, { es: 'tortuga', pt: 'tartaruga' },
        { es: 'águila', pt: 'águia' }, { es: 'búho', pt: 'coruja' }, { es: 'loro', pt: 'papagaio' },
        { es: 'pato', pt: 'pato' }, { es: 'ganso', pt: 'ganso' }, { es: 'cisne', pt: 'cisne' },
        { es: 'ciervo', pt: 'veado' }, { es: 'jabalí', pt: 'javali' }, { es: 'ardilla', pt: 'esquilo' },
        { es: 'murciélago', pt: 'morcego' }, { es: 'araña', pt: 'aranha' }, { es: 'mosca', pt: 'mosca' },
        { es: 'mosquito', pt: 'mosquito' }, { es: 'cucaracha', pt: 'barata' }, { es: 'grillo', pt: 'grilo' },
        { es: 'caracol', pt: 'caracol' }, { es: 'gusano', pt: 'verme' }, { es: 'lombriz', pt: 'minhoca' },
    ],

    // COMIDA Y BEBIDA (80+ palabras)
    comida: [
        { es: 'pan', pt: 'pão' }, { es: 'agua', pt: 'água' }, { es: 'leche', pt: 'leite' },
        { es: 'carne', pt: 'carne' }, { es: 'pollo', pt: 'frango' }, { es: 'pescado', pt: 'peixe' },
        { es: 'arroz', pt: 'arroz' }, { es: 'frijoles', pt: 'feijão' }, { es: 'huevo', pt: 'ovo' },
        { es: 'queso', pt: 'queijo' }, { es: 'mantequilla', pt: 'manteiga' }, { es: 'sal', pt: 'sal' },
        { es: 'azúcar', pt: 'açúcar' }, { es: 'café', pt: 'café' }, { es: 'té', pt: 'chá' },
        { es: 'manzana', pt: 'maçã' }, { es: 'naranja', pt: 'laranja' }, { es: 'plátano', pt: 'banana' },
        { es: 'uva', pt: 'uva' }, { es: 'fresa', pt: 'morango' }, { es: 'limón', pt: 'limão' },
        { es: 'sandía', pt: 'melancia' }, { es: 'melón', pt: 'melão' }, { es: 'piña', pt: 'abacaxi' },
        { es: 'mango', pt: 'manga' }, { es: 'pera', pt: 'pera' }, { es: 'durazno', pt: 'pêssego' },
        { es: 'cereza', pt: 'cereja' }, { es: 'coco', pt: 'coco' }, { es: 'aguacate', pt: 'abacate' },
        { es: 'tomate', pt: 'tomate' }, { es: 'lechuga', pt: 'alface' }, { es: 'cebolla', pt: 'cebola' },
        { es: 'ajo', pt: 'alho' }, { es: 'zanahoria', pt: 'cenoura' }, { es: 'papa', pt: 'batata' },
        { es: 'calabaza', pt: 'abóbora' }, { es: 'pepino', pt: 'pepino' }, { es: 'pimiento', pt: 'pimentão' },
        { es: 'brócoli', pt: 'brócolis' }, { es: 'espinaca', pt: 'espinafre' }, { es: 'maíz', pt: 'milho' },
        { es: 'pasta', pt: 'macarrão' }, { es: 'sopa', pt: 'sopa' }, { es: 'ensalada', pt: 'salada' },
        { es: 'helado', pt: 'sorvete' }, { es: 'pastel', pt: 'bolo' }, { es: 'galleta', pt: 'biscoito' },
        { es: 'chocolate', pt: 'chocolate' }, { es: 'caramelo', pt: 'doce' }, { es: 'miel', pt: 'mel' },
        { es: 'aceite', pt: 'azeite' }, { es: 'vinagre', pt: 'vinagre' }, { es: 'pimienta', pt: 'pimenta' },
        { es: 'salsa', pt: 'molho' }, { es: 'mostaza', pt: 'mostarda' }, { es: 'mayonesa', pt: 'maionese' },
        { es: 'ketchup', pt: 'ketchup' }, { es: 'jamón', pt: 'presunto' }, { es: 'tocino', pt: 'bacon' },
        { es: 'salchicha', pt: 'salsicha' }, { es: 'hamburguesa', pt: 'hambúrguer' }, { es: 'pizza', pt: 'pizza' },
        { es: 'sándwich', pt: 'sanduíche' }, { es: 'taco', pt: 'taco' }, { es: 'burrito', pt: 'burrito' },
        { es: 'vino', pt: 'vinho' }, { es: 'cerveza', pt: 'cerveja' }, { es: 'jugo', pt: 'suco' },
        { es: 'refresco', pt: 'refrigerante' }, { es: 'yogur', pt: 'iogurte' }, { es: 'cereal', pt: 'cereal' },
    ],

    // FAMILIA (30+ palabras)
    familia: [
        { es: 'madre', pt: 'mãe' }, { es: 'padre', pt: 'pai' }, { es: 'hijo', pt: 'filho' },
        { es: 'hija', pt: 'filha' }, { es: 'hermano', pt: 'irmão' }, { es: 'hermana', pt: 'irmã' },
        { es: 'abuelo', pt: 'avô' }, { es: 'abuela', pt: 'avó' }, { es: 'tío', pt: 'tio' },
        { es: 'tía', pt: 'tia' }, { es: 'primo', pt: 'primo' }, { es: 'prima', pt: 'prima' },
        { es: 'sobrino', pt: 'sobrinho' }, { es: 'sobrina', pt: 'sobrinha' }, { es: 'nieto', pt: 'neto' },
        { es: 'nieta', pt: 'neta' }, { es: 'esposo', pt: 'esposo' }, { es: 'esposa', pt: 'esposa' },
        { es: 'novio', pt: 'namorado' }, { es: 'novia', pt: 'namorada' }, { es: 'suegro', pt: 'sogro' },
        { es: 'suegra', pt: 'sogra' }, { es: 'yerno', pt: 'genro' }, { es: 'nuera', pt: 'nora' },
        { es: 'cuñado', pt: 'cunhado' }, { es: 'cuñada', pt: 'cunhada' }, { es: 'padrino', pt: 'padrinho' },
        { es: 'madrina', pt: 'madrinha' }, { es: 'ahijado', pt: 'afilhado' }, { es: 'gemelo', pt: 'gêmeo' },
    ],

    // CUERPO HUMANO (40+ palabras)
    cuerpo: [
        { es: 'cabeza', pt: 'cabeça' }, { es: 'ojo', pt: 'olho' }, { es: 'nariz', pt: 'nariz' },
        { es: 'boca', pt: 'boca' }, { es: 'oreja', pt: 'orelha' }, { es: 'mano', pt: 'mão' },
        { es: 'pie', pt: 'pé' }, { es: 'brazo', pt: 'braço' }, { es: 'pierna', pt: 'perna' },
        { es: 'corazón', pt: 'coração' }, { es: 'estómago', pt: 'estômago' }, { es: 'dedo', pt: 'dedo' },
        { es: 'cabello', pt: 'cabelo' }, { es: 'ceja', pt: 'sobrancelha' }, { es: 'pestaña', pt: 'cílio' },
        { es: 'frente', pt: 'testa' }, { es: 'mejilla', pt: 'bochecha' }, { es: 'barbilla', pt: 'queixo' },
        { es: 'cuello', pt: 'pescoço' }, { es: 'hombro', pt: 'ombro' }, { es: 'pecho', pt: 'peito' },
        { es: 'espalda', pt: 'costas' }, { es: 'cintura', pt: 'cintura' }, { es: 'cadera', pt: 'quadril' },
        { es: 'rodilla', pt: 'joelho' }, { es: 'tobillo', pt: 'tornozelo' }, { es: 'codo', pt: 'cotovelo' },
        { es: 'muñeca', pt: 'pulso' }, { es: 'uña', pt: 'unha' }, { es: 'pulmón', pt: 'pulmão' },
        { es: 'hígado', pt: 'fígado' }, { es: 'riñón', pt: 'rim' }, { es: 'cerebro', pt: 'cérebro' },
        { es: 'diente', pt: 'dente' }, { es: 'lengua', pt: 'língua' }, { es: 'labio', pt: 'lábio' },
        { es: 'garganta', pt: 'garganta' }, { es: 'sangre', pt: 'sangue' }, { es: 'hueso', pt: 'osso' },
        { es: 'músculo', pt: 'músculo' }, { es: 'piel', pt: 'pele' },
    ],

    // COLORES (20+ palabras)
    colores: [
        { es: 'rojo', pt: 'vermelho' }, { es: 'azul', pt: 'azul' }, { es: 'verde', pt: 'verde' },
        { es: 'amarillo', pt: 'amarelo' }, { es: 'negro', pt: 'preto' }, { es: 'blanco', pt: 'branco' },
        { es: 'naranja', pt: 'laranja' }, { es: 'rosa', pt: 'rosa' }, { es: 'morado', pt: 'roxo' },
        { es: 'marrón', pt: 'marrom' }, { es: 'gris', pt: 'cinza' }, { es: 'dorado', pt: 'dourado' },
        { es: 'plateado', pt: 'prateado' }, { es: 'celeste', pt: 'azul claro' }, { es: 'turquesa', pt: 'turquesa' },
        { es: 'violeta', pt: 'violeta' }, { es: 'beige', pt: 'bege' }, { es: 'crema', pt: 'creme' },
    ],

    // NÚMEROS (30+ palabras)
    numeros: [
        { es: 'uno', pt: 'um' }, { es: 'dos', pt: 'dois' }, { es: 'tres', pt: 'três' },
        { es: 'cuatro', pt: 'quatro' }, { es: 'cinco', pt: 'cinco' }, { es: 'seis', pt: 'seis' },
        { es: 'siete', pt: 'sete' }, { es: 'ocho', pt: 'oito' }, { es: 'nueve', pt: 'nove' },
        { es: 'diez', pt: 'dez' }, { es: 'once', pt: 'onze' }, { es: 'doce', pt: 'doze' },
        { es: 'trece', pt: 'treze' }, { es: 'catorce', pt: 'catorze' }, { es: 'quince', pt: 'quinze' },
        { es: 'veinte', pt: 'vinte' }, { es: 'treinta', pt: 'trinta' }, { es: 'cuarenta', pt: 'quarenta' },
        { es: 'cincuenta', pt: 'cinquenta' }, { es: 'sesenta', pt: 'sessenta' }, { es: 'setenta', pt: 'setenta' },
        { es: 'ochenta', pt: 'oitenta' }, { es: 'noventa', pt: 'noventa' }, { es: 'cien', pt: 'cem' },
        { es: 'mil', pt: 'mil' }, { es: 'millón', pt: 'milhão' }, { es: 'primero', pt: 'primeiro' },
        { es: 'segundo', pt: 'segundo' }, { es: 'tercero', pt: 'terceiro' }, { es: 'último', pt: 'último' },
    ],

    // CASA Y MUEBLES (60+ palabras)
    casa: [
        { es: 'casa', pt: 'casa' }, { es: 'puerta', pt: 'porta' }, { es: 'ventana', pt: 'janela' },
        { es: 'cocina', pt: 'cozinha' }, { es: 'baño', pt: 'banheiro' }, { es: 'habitación', pt: 'quarto' },
        { es: 'sala', pt: 'sala' }, { es: 'comedor', pt: 'sala de jantar' }, { es: 'jardín', pt: 'jardim' },
        { es: 'garaje', pt: 'garagem' }, { es: 'sótano', pt: 'porão' }, { es: 'ático', pt: 'sótão' },
        { es: 'silla', pt: 'cadeira' }, { es: 'mesa', pt: 'mesa' }, { es: 'cama', pt: 'cama' },
        { es: 'sofá', pt: 'sofá' }, { es: 'espejo', pt: 'espelho' }, { es: 'lámpara', pt: 'lâmpada' },
        { es: 'armario', pt: 'armário' }, { es: 'estante', pt: 'estante' }, { es: 'cajón', pt: 'gaveta' },
        { es: 'escalera', pt: 'escada' }, { es: 'piso', pt: 'piso' }, { es: 'techo', pt: 'teto' },
        { es: 'pared', pt: 'parede' }, { es: 'alfombra', pt: 'tapete' }, { es: 'cortina', pt: 'cortina' },
        { es: 'almohada', pt: 'travesseiro' }, { es: 'sábana', pt: 'lençol' }, { es: 'manta', pt: 'cobertor' },
        { es: 'toalla', pt: 'toalha' }, { es: 'jabón', pt: 'sabonete' }, { es: 'champú', pt: 'shampoo' },
        { es: 'cepillo', pt: 'escova' }, { es: 'peine', pt: 'pente' }, { es: 'secador', pt: 'secador' },
        { es: 'refrigerador', pt: 'geladeira' }, { es: 'estufa', pt: 'fogão' }, { es: 'horno', pt: 'forno' },
        { es: 'microondas', pt: 'micro-ondas' }, { es: 'lavadora', pt: 'máquina de lavar' },
        { es: 'plancha', pt: 'ferro' }, { es: 'aspiradora', pt: 'aspirador' }, { es: 'sartén', pt: 'frigideira' },
        { es: 'olla', pt: 'panela' }, { es: 'plato', pt: 'prato' }, { es: 'vaso', pt: 'copo' },
        { es: 'taza', pt: 'xícara' }, { es: 'cuchara', pt: 'colher' }, { es: 'tenedor', pt: 'garfo' },
        { es: 'cuchillo', pt: 'faca' }, { es: 'servilleta', pt: 'guardanapo' },
    ],

    // ROPA (40+ palabras)
    ropa: [
        { es: 'camisa', pt: 'camisa' }, { es: 'pantalón', pt: 'calça' }, { es: 'zapato', pt: 'sapato' },
        { es: 'vestido', pt: 'vestido' }, { es: 'falda', pt: 'saia' }, { es: 'chaqueta', pt: 'jaqueta' },
        { es: 'abrigo', pt: 'casaco' }, { es: 'suéter', pt: 'suéter' }, { es: 'camiseta', pt: 'camiseta' },
        { es: 'sombrero', pt: 'chapéu' }, { es: 'gorra', pt: 'boné' }, { es: 'bufanda', pt: 'cachecol' },
        { es: 'guantes', pt: 'luvas' }, { es: 'calcetines', pt: 'meias' }, { es: 'corbata', pt: 'gravata' },
        { es: 'cinturón', pt: 'cinto' }, { es: 'bolsa', pt: 'bolsa' }, { es: 'cartera', pt: 'carteira' },
        { es: 'anillo', pt: 'anel' }, { es: 'collar', pt: 'colar' }, { es: 'pulsera', pt: 'pulseira' },
        { es: 'pendientes', pt: 'brincos' }, { es: 'reloj', pt: 'relógio' }, { es: 'gafas', pt: 'óculos' },
        { es: 'paraguas', pt: 'guarda-chuva' }, { es: 'bota', pt: 'bota' }, { es: 'sandalia', pt: 'sandália' },
        { es: 'zapatilla', pt: 'tênis' }, { es: 'traje', pt: 'terno' }, { es: 'pijama', pt: 'pijama' },
        { es: 'ropa interior', pt: 'roupa íntima' }, { es: 'sostén', pt: 'sutiã' }, { es: 'shorts', pt: 'shorts' },
        { es: 'bermuda', pt: 'bermuda' }, { es: 'bikini', pt: 'biquíni' }, { es: 'traje de baño', pt: 'maiô' },
    ],

    // TIEMPO Y CLIMA (30+ palabras)
    tiempo: [
        { es: 'día', pt: 'dia' }, { es: 'noche', pt: 'noite' }, { es: 'mañana', pt: 'manhã' },
        { es: 'tarde', pt: 'tarde' }, { es: 'semana', pt: 'semana' }, { es: 'mes', pt: 'mês' },
        { es: 'año', pt: 'ano' }, { es: 'hora', pt: 'hora' }, { es: 'minuto', pt: 'minuto' },
        { es: 'segundo', pt: 'segundo' }, { es: 'hoy', pt: 'hoje' }, { es: 'ayer', pt: 'ontem' },
        { es: 'mañana', pt: 'amanhã' }, { es: 'lunes', pt: 'segunda-feira' }, { es: 'martes', pt: 'terça-feira' },
        { es: 'miércoles', pt: 'quarta-feira' }, { es: 'jueves', pt: 'quinta-feira' }, { es: 'viernes', pt: 'sexta-feira' },
        { es: 'sábado', pt: 'sábado' }, { es: 'domingo', pt: 'domingo' }, { es: 'enero', pt: 'janeiro' },
        { es: 'febrero', pt: 'fevereiro' }, { es: 'marzo', pt: 'março' }, { es: 'abril', pt: 'abril' },
        { es: 'mayo', pt: 'maio' }, { es: 'junio', pt: 'junho' }, { es: 'julio', pt: 'julho' },
        { es: 'agosto', pt: 'agosto' }, { es: 'septiembre', pt: 'setembro' }, { es: 'octubre', pt: 'outubro' },
        { es: 'noviembre', pt: 'novembro' }, { es: 'diciembre', pt: 'dezembro' },
        { es: 'sol', pt: 'sol' }, { es: 'lluvia', pt: 'chuva' }, { es: 'nieve', pt: 'neve' },
        { es: 'viento', pt: 'vento' }, { es: 'nube', pt: 'nuvem' }, { es: 'tormenta', pt: 'tempestade' },
        { es: 'calor', pt: 'calor' }, { es: 'frío', pt: 'frio' },
    ],
};

export const VOCABULARY_INTERMEDIO = {
    // PROFESIONES (50+ palabras)
    profesiones: [
        { es: 'médico', pt: 'médico' }, { es: 'enfermero', pt: 'enfermeiro' }, { es: 'abogado', pt: 'advogado' },
        { es: 'ingeniero', pt: 'engenheiro' }, { es: 'arquitecto', pt: 'arquiteto' }, { es: 'profesor', pt: 'professor' },
        { es: 'contador', pt: 'contador' }, { es: 'periodista', pt: 'jornalista' }, { es: 'fotógrafo', pt: 'fotógrafo' },
        { es: 'chef', pt: 'chef' }, { es: 'policía', pt: 'policial' }, { es: 'bombero', pt: 'bombeiro' },
        { es: 'piloto', pt: 'piloto' }, { es: 'dentista', pt: 'dentista' }, { es: 'veterinario', pt: 'veterinário' },
        { es: 'psicólogo', pt: 'psicólogo' }, { es: 'farmacéutico', pt: 'farmacêutico' }, { es: 'científico', pt: 'cientista' },
        { es: 'programador', pt: 'programador' }, { es: 'diseñador', pt: 'designer' }, { es: 'electricista', pt: 'eletricista' },
        { es: 'plomero', pt: 'encanador' }, { es: 'carpintero', pt: 'carpinteiro' }, { es: 'mecánico', pt: 'mecânico' },
        { es: 'pintor', pt: 'pintor' }, { es: 'músico', pt: 'músico' }, { es: 'actor', pt: 'ator' },
        { es: 'cantante', pt: 'cantor' }, { es: 'bailarín', pt: 'bailarino' }, { es: 'escritor', pt: 'escritor' },
        { es: 'traductor', pt: 'tradutor' }, { es: 'secretario', pt: 'secretário' }, { es: 'recepcionista', pt: 'recepcionista' },
        { es: 'vendedor', pt: 'vendedor' }, { es: 'cajero', pt: 'caixa' }, { es: 'gerente', pt: 'gerente' },
        { es: 'director', pt: 'diretor' }, { es: 'empresario', pt: 'empresário' }, { es: 'economista', pt: 'economista' },
        { es: 'juez', pt: 'juiz' }, { es: 'político', pt: 'político' }, { es: 'soldado', pt: 'soldado' },
        { es: 'cartero', pt: 'carteiro' }, { es: 'taxista', pt: 'taxista' }, { es: 'conductor', pt: 'motorista' },
    ],

    // LUGARES (60+ palabras)
    lugares: [
        { es: 'ciudad', pt: 'cidade' }, { es: 'pueblo', pt: 'vila' }, { es: 'país', pt: 'país' },
        { es: 'calle', pt: 'rua' }, { es: 'avenida', pt: 'avenida' }, { es: 'plaza', pt: 'praça' },
        { es: 'parque', pt: 'parque' }, { es: 'hospital', pt: 'hospital' }, { es: 'escuela', pt: 'escola' },
        { es: 'universidad', pt: 'universidade' }, { es: 'biblioteca', pt: 'biblioteca' }, { es: 'museo', pt: 'museu' },
        { es: 'teatro', pt: 'teatro' }, { es: 'cine', pt: 'cinema' }, { es: 'estadio', pt: 'estádio' },
        { es: 'gimnasio', pt: 'academia' }, { es: 'piscina', pt: 'piscina' }, { es: 'banco', pt: 'banco' },
        { es: 'oficina', pt: 'escritório' }, { es: 'fábrica', pt: 'fábrica' }, { es: 'tienda', pt: 'loja' },
        { es: 'supermercado', pt: 'supermercado' }, { es: 'farmacia', pt: 'farmácia' }, { es: 'panadería', pt: 'padaria' },
        { es: 'carnicería', pt: 'açougue' }, { es: 'peluquería', pt: 'salão de beleza' }, { es: 'restaurante', pt: 'restaurante' },
        { es: 'cafetería', pt: 'cafeteria' }, { es: 'bar', pt: 'bar' }, { es: 'discoteca', pt: 'balada' },
        { es: 'hotel', pt: 'hotel' }, { es: 'aeropuerto', pt: 'aeroporto' }, { es: 'estación', pt: 'estação' },
        { es: 'puerto', pt: 'porto' }, { es: 'iglesia', pt: 'igreja' }, { es: 'templo', pt: 'templo' },
        { es: 'cementerio', pt: 'cemitério' }, { es: 'playa', pt: 'praia' }, { es: 'montaña', pt: 'montanha' },
        { es: 'río', pt: 'rio' }, { es: 'lago', pt: 'lago' }, { es: 'mar', pt: 'mar' },
        { es: 'bosque', pt: 'floresta' }, { es: 'desierto', pt: 'deserto' }, { es: 'isla', pt: 'ilha' },
        { es: 'frontera', pt: 'fronteira' }, { es: 'embajada', pt: 'embaixada' }, { es: 'consulado', pt: 'consulado' },
    ],

    // EMOCIONES Y SENTIMIENTOS (40+ palabras)
    emociones: [
        { es: 'feliz', pt: 'feliz' }, { es: 'triste', pt: 'triste' }, { es: 'enojado', pt: 'bravo' },
        { es: 'asustado', pt: 'assustado' }, { es: 'sorprendido', pt: 'surpreso' }, { es: 'emocionado', pt: 'emocionado' },
        { es: 'preocupado', pt: 'preocupado' }, { es: 'ansioso', pt: 'ansioso' }, { es: 'nervioso', pt: 'nervoso' },
        { es: 'tranquilo', pt: 'tranquilo' }, { es: 'cansado', pt: 'cansado' }, { es: 'aburrido', pt: 'entediado' },
        { es: 'confundido', pt: 'confuso' }, { es: 'frustrado', pt: 'frustrado' }, { es: 'orgulloso', pt: 'orgulhoso' },
        { es: 'avergonzado', pt: 'envergonhado' }, { es: 'celoso', pt: 'ciumento' }, { es: 'enamorado', pt: 'apaixonado' },
        { es: 'solitario', pt: 'solitário' }, { es: 'nostálgico', pt: 'nostálgico' }, { es: 'esperanzado', pt: 'esperançoso' },
        { es: 'agradecido', pt: 'grato' }, { es: 'satisfecho', pt: 'satisfeito' }, { es: 'decepcionado', pt: 'decepcionado' },
        { es: 'entusiasmado', pt: 'entusiasmado' }, { es: 'relajado', pt: 'relaxado' }, { es: 'estresado', pt: 'estressado' },
        { es: 'motivado', pt: 'motivado' }, { es: 'desanimado', pt: 'desanimado' }, { es: 'aliviado', pt: 'aliviado' },
        { es: 'amor', pt: 'amor' }, { es: 'odio', pt: 'ódio' }, { es: 'miedo', pt: 'medo' },
        { es: 'alegría', pt: 'alegria' }, { es: 'tristeza', pt: 'tristeza' }, { es: 'rabia', pt: 'raiva' },
    ],

    // TECNOLOGÍA (40+ palabras)
    tecnologia: [
        { es: 'computadora', pt: 'computador' }, { es: 'teléfono', pt: 'telefone' }, { es: 'celular', pt: 'celular' },
        { es: 'tableta', pt: 'tablet' }, { es: 'teclado', pt: 'teclado' }, { es: 'ratón', pt: 'mouse' },
        { es: 'pantalla', pt: 'tela' }, { es: 'impresora', pt: 'impressora' }, { es: 'escáner', pt: 'scanner' },
        { es: 'cámara', pt: 'câmera' }, { es: 'micrófono', pt: 'microfone' }, { es: 'auriculares', pt: 'fones de ouvido' },
        { es: 'internet', pt: 'internet' }, { es: 'wifi', pt: 'wifi' }, { es: 'red', pt: 'rede' },
        { es: 'sitio web', pt: 'site' }, { es: 'aplicación', pt: 'aplicativo' }, { es: 'programa', pt: 'programa' },
        { es: 'archivo', pt: 'arquivo' }, { es: 'carpeta', pt: 'pasta' }, { es: 'contraseña', pt: 'senha' },
        { es: 'correo electrónico', pt: 'e-mail' }, { es: 'mensaje', pt: 'mensagem' }, { es: 'video', pt: 'vídeo' },
        { es: 'foto', pt: 'foto' }, { es: 'descarga', pt: 'download' }, { es: 'subir', pt: 'upload' },
        { es: 'batería', pt: 'bateria' }, { es: 'cargador', pt: 'carregador' }, { es: 'cable', pt: 'cabo' },
        { es: 'enchufe', pt: 'tomada' }, { es: 'televisión', pt: 'televisão' }, { es: 'control remoto', pt: 'controle remoto' },
        { es: 'robot', pt: 'robô' }, { es: 'inteligencia artificial', pt: 'inteligência artificial' },
    ],
};

export const VOCABULARY_AVANZADO = {
    // NEGOCIOS Y TRABAJO (50+ palabras)
    negocios: [
        { es: 'empresa', pt: 'empresa' }, { es: 'negocio', pt: 'negócio' }, { es: 'cliente', pt: 'cliente' },
        { es: 'proveedor', pt: 'fornecedor' }, { es: 'empleado', pt: 'funcionário' }, { es: 'jefe', pt: 'chefe' },
        { es: 'reunión', pt: 'reunião' }, { es: 'contrato', pt: 'contrato' }, { es: 'factura', pt: 'fatura' },
        { es: 'presupuesto', pt: 'orçamento' }, { es: 'inversión', pt: 'investimento' }, { es: 'ganancia', pt: 'lucro' },
        { es: 'pérdida', pt: 'prejuízo' }, { es: 'deuda', pt: 'dívida' }, { es: 'préstamo', pt: 'empréstimo' },
        { es: 'impuesto', pt: 'imposto' }, { es: 'salario', pt: 'salário' }, { es: 'comisión', pt: 'comissão' },
        { es: 'descuento', pt: 'desconto' }, { es: 'precio', pt: 'preço' }, { es: 'costo', pt: 'custo' },
        { es: 'venta', pt: 'venda' }, { es: 'compra', pt: 'compra' }, { es: 'mercado', pt: 'mercado' },
        { es: 'competencia', pt: 'concorrência' }, { es: 'estrategia', pt: 'estratégia' }, { es: 'objetivo', pt: 'objetivo' },
        { es: 'proyecto', pt: 'projeto' }, { es: 'plazo', pt: 'prazo' }, { es: 'entrega', pt: 'entrega' },
        { es: 'calidad', pt: 'qualidade' }, { es: 'garantía', pt: 'garantia' }, { es: 'devolución', pt: 'devolução' },
        { es: 'reclamación', pt: 'reclamação' }, { es: 'solución', pt: 'solução' }, { es: 'problema', pt: 'problema' },
        { es: 'éxito', pt: 'sucesso' }, { es: 'fracaso', pt: 'fracasso' }, { es: 'crecimiento', pt: 'crescimento' },
        { es: 'desarrollo', pt: 'desenvolvimento' }, { es: 'innovación', pt: 'inovação' }, { es: 'tecnología', pt: 'tecnologia' },
    ],

    // EDUCACIÓN (40+ palabras)
    educacion: [
        { es: 'estudiante', pt: 'estudante' }, { es: 'alumno', pt: 'aluno' }, { es: 'maestro', pt: 'mestre' },
        { es: 'clase', pt: 'aula' }, { es: 'curso', pt: 'curso' }, { es: 'asignatura', pt: 'disciplina' },
        { es: 'examen', pt: 'exame' }, { es: 'prueba', pt: 'prova' }, { es: 'calificación', pt: 'nota' },
        { es: 'tarea', pt: 'tarefa' }, { es: 'trabajo', pt: 'trabalho' }, { es: 'investigación', pt: 'pesquisa' },
        { es: 'tesis', pt: 'tese' }, { es: 'diploma', pt: 'diploma' }, { es: 'título', pt: 'título' },
        { es: 'graduación', pt: 'formatura' }, { es: 'beca', pt: 'bolsa de estudos' }, { es: 'matrícula', pt: 'matrícula' },
        { es: 'semestre', pt: 'semestre' }, { es: 'vacaciones', pt: 'férias' }, { es: 'horario', pt: 'horário' },
        { es: 'libro', pt: 'livro' }, { es: 'cuaderno', pt: 'caderno' }, { es: 'bolígrafo', pt: 'caneta' },
        { es: 'lápiz', pt: 'lápis' }, { es: 'borrador', pt: 'borracha' }, { es: 'regla', pt: 'régua' },
        { es: 'pizarra', pt: 'quadro' }, { es: 'proyector', pt: 'projetor' }, { es: 'laboratorio', pt: 'laboratório' },
    ],

    // SALUD (40+ palabras)
    salud: [
        { es: 'doctor', pt: 'doutor' }, { es: 'paciente', pt: 'paciente' }, { es: 'enfermedad', pt: 'doença' },
        { es: 'síntoma', pt: 'sintoma' }, { es: 'dolor', pt: 'dor' }, { es: 'fiebre', pt: 'febre' },
        { es: 'tos', pt: 'tosse' }, { es: 'gripe', pt: 'gripe' }, { es: 'resfriado', pt: 'resfriado' },
        { es: 'alergia', pt: 'alergia' }, { es: 'infección', pt: 'infecção' }, { es: 'virus', pt: 'vírus' },
        { es: 'bacteria', pt: 'bactéria' }, { es: 'vacuna', pt: 'vacina' }, { es: 'medicamento', pt: 'medicamento' },
        { es: 'pastilla', pt: 'comprimido' }, { es: 'jarabe', pt: 'xarope' }, { es: 'inyección', pt: 'injeção' },
        { es: 'receta', pt: 'receita' }, { es: 'tratamiento', pt: 'tratamento' }, { es: 'cirugía', pt: 'cirurgia' },
        { es: 'operación', pt: 'operação' }, { es: 'urgencia', pt: 'urgência' }, { es: 'emergencia', pt: 'emergência' },
        { es: 'ambulancia', pt: 'ambulância' }, { es: 'seguro médico', pt: 'plano de saúde' },
        { es: 'consultorio', pt: 'consultório' }, { es: 'clínica', pt: 'clínica' }, { es: 'análisis', pt: 'exame' },
        { es: 'radiografía', pt: 'raio-x' }, { es: 'diagnóstico', pt: 'diagnóstico' },
    ],
};
